#!/usr/bin/env node
var readline = require('readline');

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

var vars = {

};

rl.question('Name(camelCase): ', function(answer) {
  vars.name = answer.camelCase();
  vars.namePlural = vars.name + 's';
  vars.controllerName = vars.name.charAt(0).toUpperCase() + vars.name.slice(1);
  vars.schemaName = vars.controllerName + "Schema";
});

rl.question('Description: ', function(answer) {
  vars.description = answer;
});

var author = {};

rl.question('First Name: ', function(answer) {
  author.firstName = answer;
});

rl.question('Last Name: ', function(answer) {
  author.lastName = answer;
});

rl.question('Email: ', function(answer) {
  author.email = answer;
});

vars.author = author.firstName + ' ' + author.lastName + ' <' + author.email + '>';

//pass to template compiler
require('./app')(vars);

//helpers
String.prototype.camelCase = function(){
  var newString = '';
  var lastEditedIndex;
  for (var i = 0; i < this.length; i++){
    if(this[i] == ' ' || this[i] == '-' || this[i] == '_'){
      newString += this[i+1].toUpperCase();
      lastEditedIndex = i+1;
    }
    else if(lastEditedIndex !== i) newString += this[i].toLowerCase();
  }
  return newString;
};